export const START_TIMER = 'START_TIMER'
export const STOP_TIMER = 'STOP_TIMER'
export const CANCEL_TIMER = 'CANCEL_TIMER'

export const FETCH_RESULTS_REQUEST = 'FETCH_RESULTS_REQUEST'
export const FETCH_RESULTS_SUCCESS = 'FETCH_RESULTS_SUCCESS'
export const FETCH_RESULTS_FAILURE = 'FETCH_RESULTS_FAILURE'

export const SELECT_TOWN = 'SELECT_TOWN'
